CREATE DATABASE customer_behavior;
USE customer_behavior;
SHOW tables;

SELECT * FROM customer LIMIT 10;

-- What is the total revenue generated by male and female customers? 

SELECT gender,SUM(purchase_amount) as total_revenue_generated
FROM customer
GROUP BY gender;

-- Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT avg(purchase_amount) FROM customer);

-- Which are the top 5 products with the highest average review rating?
WITH review_rating AS 
	(SELECT item_purchased,ROUND(average,2) as average_review_rating,
	DENSE_RANK() OVER(ORDER BY ROUND(average,2) DESC) as dr
	FROM 
		(SELECT item_purchased,AVG(review_rating) as average
		FROM customer
		GROUP BY item_purchased
		)t
		)

SELECT item_purchased,average_review_rating
FROM review_rating
WHERE dr <= 5;

-- Compare the average Purchase amounts between Standard and Express Shipping?
SELECT shipping_type,ROUND(AVG(purchase_amount),2) as avg_purchase_amount
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total_revenue
-- Between subscribers and non-subscribers?

SELECT status,avg(purchase_amount) as avg_spent,SUM(purchase_amount) as total_revenue 
FROM 
	(SELECT 
	CASE 
		WHEN subscription_status = 'Yes' 
		THEN 'subscriber' ELSE 'non-subscribers' 
		END as status,purchase_amount
	FROM customer
	)t
GROUP BY status;

-- Which 5 products have the highest percentage of purchases with discount applied?

SELECT item_purchased,
ROUND(SUM(
	CASE 
		WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)*100.0/
        COUNT(*),2) as purchase_percentage
FROM customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5;

-- Segment customers into NEW,Returning, and Loyal based on their total number of previous purchases 
-- and show the count of each segment?

WITH customer_status AS
	(SELECT customer_id,previous_purchases,
	CASE
		WHEN previous_purchases  = 1 THEN 'New'
		WHEN previous_purchases >= 2 AND previous_purchases <= 10 THEN 'Returning' 
		ELSE 'Loyal' END as customer_segment
	FROM customer)

SELECT customer_segment,COUNT(customer_id) as 'Total customers in each segment'
FROM customer_status
GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category?

SELECT category,item_purchased,total_purchases
FROM
	(SELECT category,item_purchased,COUNT(*) as total_purchases,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) as ranking
	FROM customer
	GROUP BY category,item_purchased
	)t
WHERE ranking <= 3; 

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group?

SELECT age_group,SUM(purchase_amount) as contribution,
ROUND(100.0*SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer),2) as 'contribution%'
FROM customer
GROUP BY age_group
ORDER BY contribution DESC



